apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: ns2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: yossefsameh/my-app:13
        ports:
          - name: my-port
            containerPort: 5000
         
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: ns2
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: app
